### ISSUE TITLE
Remove clicking noise when 3D print toggled via redstone

### ISSUE THREAD

**Issue by znepb** [SwitchCraftCC/sc-peripherals#16]
I feel that the noises are made when a 3D print is toggled off/on can be annoying or distracting, especially when automated. Is it possible that this feature could be removed?

**Comment by Wojbie** [comment]
How is that different from piston or door/trapdoor making noise when changing state?

**Comment by hugeblank** [comment]
@Wojbie only prints that have the button flag set make noise for one, for another doors and trapdoors (at least the wood ones) behave more like levers than they do buttons. 

So basically there's two things going on here now. An inconsistency, and a request. The inconsistency is that non-button prints do not make noise, but button prints do. The request is that the noise for button prints be removed. I think the request has some ground because it would bring parity across all prints. The other option is both non-button and button classed prints make noise and I'm not sure how I feel about that.
