### ISSUE TITLE
Wrong lightWhenOff and lightWhenOn NBT Data on new prints causes them to not stack with old ones

### ISSUE THREAD

**Issue by creeloper27** [SwitchCraftCC/sc-peripherals#41]
While investigating another possible bug I realized that my new 3d prints do not stack with my old ones created a few months ago (created from the same `.3dj` file).

This is probably related to #42 but seems like a different problem.

The reason seems to be wrong NBT Data `lightWhenOff` and `lightWhenOn` that should be set to `0b` as specified in the `.3dj` but instead are set to `1b`.

This causes the new prints to not stack with the old ones (and probably causes them to emit some light even tho they shouldn't I guess).

Example:
`black.3dj`
```
{
    "label": "black",
    "isButton": false,
    "collideWhenOn": true,
    "collideWhenOff": true,
    "lightLevel": 0,
    "redstoneLevel": 0,
    "shapesOff": [
        { "bounds": [0,0,0,16,16,16], "texture": "sc-peripherals:block/white", "tint": "000000"}
    ],
    "shapesOn": []
}
```
old `black.3dj` print (from a few months ago):
![image](https://github.com/SwitchCraftCC/sc-peripherals/assets/20074177/220a8692-8fb0-458e-a464-b31a140f766a)

new `black.3dj` print (from a few minutes ago):
![image](https://github.com/SwitchCraftCC/sc-peripherals/assets/20074177/32731f1a-5e1a-4a7b-901b-29bc2f3374d6)

**Comment by Lemmmy** [comment]
The default tag issue is a bigger issue than not stacking. I've fixed that. When chunks with these prints in them (either as blocks, or as items) are saved and then re-loaded, they'll regain the correct data, and then be able to stack again. Since we don't have datafixers to play with, that's the only sensible way to perform data migration, so your stacking problems should resolve themselves over time. If they don't, feel free to re-open this issue.
