### ISSUE TITLE
Add support for minecraft:block/barrier

### ISSUE THREAD

**Issue by creeloper27** [SwitchCraftCC/sc-peripherals#44]
Right now the only way to print invisible blocks is by using `minecraft:block/redstone_dust_overlay`, it would be nice especially for new players to be able to use `minecraft:block/barrier` to print invisible blocks instead (which can be quite useful at times), tho right now using `minecraft:block/barrier` produces an invalid texture.

Example:
full block `minecraft:block/redstone_dust_overlay` print:
![image](https://github.com/SwitchCraftCC/sc-peripherals/assets/20074177/11b3b199-899f-4891-837f-38854ffc79d7)

full block `minecraft:block/barrier` print:
![image](https://github.com/SwitchCraftCC/sc-peripherals/assets/20074177/7cf12351-5c99-4cfc-b024-912220cc9d9d)

**Comment by scmcgowen** [comment]
the texture `minecraft:block/barrier` simply does not exist, if they were to add a specific invisible texture, it’d probably be something like `sc-peripherals:invisible`

**Comment by Kan18** [comment]
for consistency with OpenComputers it might be easiest to interpret an empty string as an invisible texture

**Comment by Lemmmy** [comment]
I didn't want to support invisible prints, but since I have little control over which textures 'look' invisible to the client, I've allowed `null` textures in the printer peripheral. Everywhere else already handled this behavior correctly - a null texture won't render a shape at all, so performance-wise, it's preferable to using a weird/arbitrary texture.

This also means that 6_4's stupid 'force field' prints won't cause goofy artifacts with clouds anymore.
