### ISSUE TITLE
Feature Request - Add a way to 'Clone Prints' OR get print data to be able to reprint/change colors etc.

### ISSUE THREAD

**Issue by stealthy-coder** [SwitchCraftCC/sc-peripherals#7]
Basicly, i'd like it so that i can later if i lose one of my 3dprint files so that i can reprint a print and have more of it and even better if i can just get the raw printdata where i can print it again.

**Comment by Kan18** [comment]
maybe add a way for print data to be read through getItemDetail?

**Comment by Lemmmy** [comment]
From an SC economy perspective, I think this would be a kick to any business that plans to sell 3D prints, as you could just buy one and clone it yourself. Not that you can't recreate them now anyway, but it significantly lowers the skill barrier to do so

**Comment by DukeAbigor** [comment]
Bit of a leak since I won't actively revealing this fact until the day of the first competition, but I've already commissioned one of my modeller friends to make one of a kind themed trophies for each week's winner of the arena with the intention of deleting the print's file after that week is won and never let another copy exist. Would kinda put a big hamper on it if they could be cloned

**Comment by Lemmmy** [comment]
I'll leave this open for a bit to see if anyone can reasonably sway me but I think this is a 'wontfix'

**Comment by hugeblank** [comment]
> if i lose one of my 3dprint files 

An entire pastebin instance has been set up. One of its benefits is to prevent a situation like this from occurring. Have data redundancy is my proposed solution to this issue.

**Comment by Kan18** [comment]
Maybe add a "unreadable" flag that 3D print sellers can set to prevent getItemDetail reading?
